name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Clean solution
      run: dotnet clean Ganz.sln

    - name: Restore dependencies
      run: dotnet restore Ganz.sln

    - name: Build solution
      run: dotnet build Ganz.sln --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test Ganz.UnitTests/Ganz.UnitTests.csproj --no-build --configuration Release --verbosity normal

    - name: Run Integration Tests
      run: dotnet test Ganz.IntegrationTests/Ganz.IntegrationTests.csproj --no-build --configuration Release --verbosity normal
